# Default configuration for Draco Assistant

# Speech recognition settings
speech:
  model: "medium" # Whisper model size (tiny, base, small, medium, large)
  language: null # Language code for transcription (null for auto-detect)
  device: null # Audio input device ID (null for default)
  samplerate: 16000
  blocksize: 8000

# LLM settings
llm:
  provider: "ollama" # LLM provider (ollama)
  model: "mistral" # Model name (mistral, llama2, codellama)
  temperature: 0.7 # Temperature for generation
  max_tokens: 150

# Command settings
commands:
  # System commands (always enabled)
  system:
    enabled: true
    commands:
      - help
      - list
      - status

  # Spotify integration
  spotify:
    enabled: false
    client_id: ""
    client_secret: ""
    redirect_uri: "http://localhost:8888/callback"
    scope: "user-read-playback-state user-modify-playback-state"

  # Smart home integration
  smart_home:
    enabled: false
    host: "http://localhost:8123"
    token: ""
    entities: [] # List of entity IDs to control

# Logging settings
logging:
  level: "INFO" # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "logs/draco.log" # Log file path
  max_size: 10485760 # Maximum log file size (10MB)
  backup_count: 5 # Number of backup files to keep
